version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.8
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.5
    - 1.3.9
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.8
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.0
    - 4.5.1
  - dependency-name: sass-loader
    versions:
    - 10.1.0
  - dependency-name: bootstrap
    versions:
    - 4.5.3
  - dependency-name: ejs
    versions:
    - 3.1.5
